### ISSUE TITLE
getReadableDataBase() throws null error

### ISSUE THREAD

**Issue by ravenet** [ajaysahani/EasyDatabase#1]
Hi,

I am impressed with this library, and I am trying to use, but I am getting null reference exception getReadableDataBase in query method always.

can you help me to fix it?

thanks

**Comment by ajaysahani** [comment]
Hi,
I will check and come back to you.
Please provide me more details.

**Comment by ajaysahani** [comment]
Hi,
Check into class which is extended EasyDatabaseContentProvider
,getSqlHelper() method you might be returning null.

**Comment by ravenet** [comment]
Hi,

Thank you for prompt response, and I check the stack trace
Error :
02-09 21:11:58.349: E/AndroidRuntime(26510): FATAL EXCEPTION: main
02-09 21:11:58.349: E/AndroidRuntime(26510): java.lang.NullPointerException
02-09 21:11:58.349: E/AndroidRuntime(26510):    at android.database.DatabaseUtils.getSqlStatementType(DatabaseUtils.java:1363)
02-09 21:11:58.349: E/AndroidRuntime(26510):    at android.database.sqlite.SQLiteDatabase.executeSql(SQLiteDatabase.java:1781)
02-09 21:11:58.349: E/AndroidRuntime(26510):    at android.database.sqlite.SQLiteDatabase.execSQL(SQLiteDatabase.java:1725)
02-09 21:11:58.349: E/AndroidRuntime(26510):    at com.techdigit.mansion.database.DatabaseHelper.onCreate(DatabaseHelper.java:34)
02-09 21:11:58.349: E/AndroidRuntime(26510):    at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:252)
02-09 21:11:58.349: E/AndroidRuntime(26510):    at android.database.sqlite.SQLiteOpenHelper.getReadableDatabase(SQLiteOpenHelper.java:188)
02-09 21:11:58.349: E/AndroidRuntime(26510):    at com.xxxx.yyyyyy.providers.BaseDatabaseContentProvider.getReadableDataBase(BaseDatabaseContentProvider.java:249)
02-09 21:11:58.349: E/AndroidRuntime(26510):    at com.xxxx.providers.BaseDatabaseContentProvider.query(BaseDatabaseContentProvider.java:157)
02-09 21:11:58.349: E/AndroidRuntime(26510):    at android.content.ContentProvider.query(ContentProvider.java:744)
02-09 21:11:58.349: E/AndroidRuntime(26510):    at android.content.ContentProvider$Transport.query(ContentProvider.java:199)
02-09 21:11:58.349: E/AndroidRuntime(26510):    at android.content.ContentResolver.query(ContentResolver.java:417)
02-09 21:11:58.349: E/AndroidRuntime(26510):    at android.content.ContentResolver.query(ContentResolver.java:360)

Step 1 : I copy databasehelp from your app
Step 2: create usercontentprovider
Step 3:  call query method to check user exists with email

public String hasUserExist(String email) {
        String memberID = "";
        String mSelectionClause = UserContentProvider.KEY_USER_EMAIL + " = ?";
        String[] selectionArgs = { "" + email };

```
    Cursor cursor = context.getContentResolver().query(
            UserContentProvider.USER_TABLE_URI, null, mSelectionClause,
            selectionArgs, null);
    if (cursor != null) {
        memberID = cursor.getString(cursor
                .getColumnIndex(UserContentProvider.KEY_ID));
        cursor.close();
    }
    return memberID;
}
```

still I am getting error, please help me.

thanks

**Comment by ravenet** [comment]
Hi  Mate,

Thanks you and I resolved. it is not library issue.

Thanks you once again.

**Comment by ajaysahani** [comment]
You are welcome.
