### ISSUE TITLE
EasyDatabaseContentProvider default primary key or _iid column

### ISSUE THREAD

**Issue by ravenet** [ajaysahani/EasyDatabase#2]
Hi Ajay,

I can see you have done an excellent job, however, there is a problem in the EasyDatabaseContentProvider you force outside caller to create _id column. For example

I am using CursorLoader manager and select all columns from the table, but this table does not have _id which is not necessary to this context. then it is throw error _id column is not found.

So in some cases, we dont need _id column at all. can you help support those cases too.

Once again thank for nice job.

**Comment by ajaysahani** [comment]
Hi ravenet,
If you want to use content provider in your project it is necessary to have _id field (Android Framework).

**Comment by ravenet** [comment]
Dear Sahani,
Thank you and I updated.
